FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# copy maven wrapper + pom ก่อน (cache dependency)
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

COPY src src

# build jar
RUN ./mvnw clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java -jar target/*.jar"]
